	
CREATE DATABASE MYLIBRARY;

CREATE TABLE THAMSO (
	TUOI_TOI_DA INT NOT NULL,
    TUOI_TOI_THIEU INT NOT NULL,
    THOI_HAN_THE INT NOT NULL,
    KHOANG_CACH_NAM_XUAT_BAN INT NOT NULL,
    TIEN_PHAT_MOI_NGAY INT NOT NULL,
    SO_SACH_TOI_DA INT NOT NULL,
    SO_NGAY_MUON_TOI_DA INT NOT NULL
);

CREATE TABLE LOAI_DOC_GIA(
  	TEN_LOAI_DOC_GIA VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE THE_LOAI_SACH(
	TEN_THE_LOAI_SACH VARCHAR(50) NOT NULL PRIMARY KEY
);
CREATE TABLE TAC_GIA(
    TEN_TAC_GIA VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE DOC_GIA (
    MA_DOC_GIA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    HO_TEN_DOC_GIA VARCHAR(50) NOT NULL,
    LOAI_DOC_GIA VARCHAR(50) NOT NULL,
    NGAY_SINH DATE,
    DIA_CHI VARCHAR(50),
    EMAIL VARCHAR(50) NOT NULL,
    NGAY_LAP_THE DATE NOT NULL,
	TONG_NO INT NOT NULL,
    CONSTRAINT FK_DOCGIA_LOAI_DOCGIA FOREIGN KEY (LOAI_DOC_GIA) REFERENCES LOAI_DOC_GIA(TEN_LOAI_DOC_GIA)
);

CREATE TABLE SACH (
    MA_SACH INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TEN_SACH VARCHAR(50) NOT NULL,
    THE_LOAI VARCHAR(50) NOT NULL,
    TAC_GIA VARCHAR(50) NOT NULL,
    NGAY_NHAP_SACH DATE,
	NHA_XUAT_BAN VARCHAR(50) NOT NULL,
    NAM_XUAT_BAN INT NOT NULL,
    TRI_GIA INT NOT NULL,
	IMAGE_PATH VARCHAR(500) NOT NULL,
    TINH_TRANG BOOLEAN NOT NULL,
    CONSTRAINT FK_SACH_THELOAISACH FOREIGN KEY (THE_LOAI) REFERENCES THE_LOAI_SACH(TEN_THE_LOAI_SACH),
    CONSTRAINT FK_SACH_TENTACGIA FOREIGN KEY (TAC_GIA) REFERENCES TAC_GIA(TEN_TAC_GIA)
);

CREATE TABLE PHIEU_MUON_TRA (
	MA_PHIEU_MUON_TRA INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    MA_DOC_GIA INT NOT NULL,
    MA_SACH INT NOT NULL,
    NGAY_MUON DATE NOT NULL,
	NGAY_TRA DATE,
	SO_NGAY_TRA_TRE INT,
	TIEN_PHAT_KY INT,
    CONSTRAINT FK_PHIEUMUONSACH_DOCGIA FOREIGN KEY (MA_DOC_GIA) REFERENCES DOC_GIA(MA_DOC_GIA),
    CONSTRAINT FK_PHIEUMUONSACH_SACH FOREIGN KEY (MA_SACH) REFERENCES SACH(MA_SACH)
);

CREATE TABLE PHIEU_THU_TIEN_PHAT (
	MA_PHIEU_THU_TIEN_PHAT INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	MA_DOC_GIA INT NOT NULL,
    SO_TIEN_THU INT,
    CON_LAI INT,
    CONSTRAINT FK_PHIEUTHUTIENPHAT_PHIEUTRASACH FOREIGN KEY (MA_DOC_GIA) REFERENCES DOC_GIA(MA_DOC_GIA)
);

CREATE TABLE BAO_CAO_THANG(
	MA_BAO_CAO_THANG INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	THANG INT NOT NULL,
    NAM INT NOT NULL,
    TONG_SO_LUOT_MUON INT NOT NULL
);
CREATE TABLE CT_BAO_CAO_THANG(
	MA_CT_BAO_CAO_THANG INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	MA_BAO_CAO_THANG INT NOT NULL,
    THE_LOAI VARCHAR(50) NOT NULL,
    SO_LUOT_MUON INT NOT NULL,
	TI_LE DECIMAL(10,2) NOT NULL,
	CONSTRAINT FK_CTBAOCAOTHANG_BAOCAOTHANG_MABAOCAO FOREIGN KEY (MA_BAO_CAO_THANG) REFERENCES BAO_CAO_THANG(MA_BAO_CAO_THANG)
);

CREATE TABLE BAO_CAO_NGAY(
	MA_BAO_CAO_NGAY INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	NGAY DATE NOT NULL,
    TEN_SACH VARCHAR(50) NOT NULL,
    NGAY_MUON DATE NOT NULL,
	SO_NGAY_TRA_TRE INT NOT NULL
);

INSERT INTO THAMSO (TUOI_TOI_DA, TUOI_TOI_THIEU, THOI_HAN_THE, KHOANG_CACH_NAM_XUAT_BAN, TIEN_PHAT_MOI_NGAY, SO_SACH_TOI_DA, SO_NGAY_MUON_TOI_DA) VALUES (55, 10, 180, 8, 1000, 5, 4)
