
CREATE DATABASE MYLIBRARY;

CREATE TABLE ADMIN_ACCOUNT (
	ADMIN_ID int AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ADMIN_NAME VARCHAR(30) NOT NULL,
    ADMIN_PASSWORD VARCHAR(30) NOT NULL
);
CREATE TABLE USER_ACCOUNT (
	USERID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	USERNAME VARCHAR(30) NOT NULL,
	USER_PASSWORD VARCHAR(30) NOT NULL
);

CREATE TABLE QUYDINH (
	TUOI_TOI_DA INT NOT NULL,
    	TUOI_TOI_THIEU INT NOT NULL,
    	THOI_HAN_THE DATETIME,
    	KHOANG_CACH_NAM_XUAT_BAN INT NOT NULL,
    	TIEN_PHAT_MOI_NGAY INT NOT NULL,
    	SO_SACH_TOI_DA INT NOT NULL,
    	SO_NGAY_MUON_TOI_DA INT NOT NULL
);

CREATE TABLE LOAI_DOC_GIA(
  	LOAI_DOCGIA VARCHAR(30) NOT NULL PRIMARY KEY
);

CREATE TABLE THE_LOAI_SACH(
	TEN_THE_LOAI_SACH VARCHAR(20) NOT NULL PRIMARY KEY
);
CREATE TABLE TAC_GIA(
    	TEN_TAC_GIA VARCHAR(30) NOT NULL PRIMARY KEY
);

CREATE TABLE DOC_GIA (
    	MA_DOC_GIA INT NOT NULL PRIMARY KEY,
    	HO_TEN_DOC_GIA VARCHAR(30) NOT NULL,
    	LOAI_DOC_GIA VARCHAR(30) NOT NULL,
    	NGAY_SINH DATETIME,
    	DIA_CHI VARCHAR(50),
    	EMAIL VARCHAR(20) NOT NULL,
    	NGAY_LAP_THE DATETIME NOT NULL,
    	CONSTRAINT FK_DOCGIA_USER FOREIGN KEY (MA_DOC_GIA) REFERENCES USER_ACCOUNT(USERID),
    	CONSTRAINT FK_DOCGIA_LOAI_DOCGIA FOREIGN KEY (LOAI_DOC_GIA) REFERENCES LOAI_DOC_GIA(LOAI_DOCGIA)
);

CREATE TABLE SACH (
    	MA_SACH CHAR(5) AUTO_INCREMENT NOT NULL PRIMARY KEY,
    	TEN_SACH VARCHAR(50) NOT NULL,
    	THE_LOAI VARCHAR(20) NOT NULL,
    	TAC_GIA VARCHAR(30) NOT NULL,
    	NGAY_NHAP_SACH DATETIME,
	NHA_XUAT_BAN VARCHAR(50) NOT NULL,
    	NAM_XUAT_BAN INT NOT NULL,
    	TRI_GIA INT NOT NULL,
    	TINH_TRANG BOOLEAN,
    	CONSTRAINT FK_SACH_THELOAISACH FOREIGN KEY (THE_LOAI) REFERENCES THE_LOAI_SACH(TEN_THE_LOAI_SACH),
    	CONSTRAINT FK_SACH_TENTACGIA FOREIGN KEY (TAC_GIA) REFERENCES TAC_GIA(TEN_TAC_GIA)
);

CREATE TABLE PHIEU_MUON_SACH (
	MA_PHIEU_MUON INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    	MA_DOC_GIA INT NOT NULL,
    	MA_SACH INT NOT NULL,
    	NGAY_MUON DATETIME NOT NULL,
);

CREATE TABLE PHIEU_TRA_SACH (
	MA_PHIEU_TRA INT NOT NULL PRIMARY KEY,
    	MA_SACH CHAR(5) NOT NULL,
    	MA_DOC_GIA INT NOT NULL,
    	NGAY_TRA DATETIME NOT NULL,
    	NGAY_MUON DATETIME NOT NULL,
    	SO_NGAY_MUON INT,
    	TIEN_PHAT_KY INT,
    	DA_TRA_SACH BOOLEAN NOT NULL,
    	CONSTRAINT FK_PHIEUTRASACH_PHIEUMUONSACH_MAPHIEUMUON FOREIGN KEY (MA_PHIEU_TRA) REFERENCES PHIEU_MUON_SACH(MA_PHIEU_MUON),
    	CONSTRAINT FK_PHIEUTRASACH_PHIEUMUONSACH_MADOCGIA FOREIGN KEY (MA_DOC_GIA) REFERENCES PHIEU_MUON_SACH(MA_DOC_GIA),
    	CONSTRAINT FK_PHIEUTRASACH_PHIEUMUONSACH_MASACH FOREIGN KEY (MA_SACH) REFERENCES PHIEU_MUON_SACH(MA_SACH)
);

CREATE TABLE PHIEU_THU_TIEN_PHAT (
	MA_PHIEU_THU_TIEN_PHAT INT NOT NULL PRIMARY KEY,
	MA_DOC_GIA INT,
    	TONG_NO INT,
    	SO_TIEN_THU INT,
    	CON_LAI INT,
    	CONSTRAINT FK_PHIEUTHUTIENPHAT_PHIEUTRASACH FOREIGN KEY (MA_DOC_GIA) REFERENCES PHIEU_TRA_SACH(MA_DOC_GIA)
);

